"""Add multitenancy

Revision ID: c1ad05a4b992
Revises: daef80a3e777
Create Date: 2026-08-19 15:31:14.889227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ad05a4b992'
down_revision: Union[str, Sequence[str], None] = 'daef80a3e777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tenant_table = op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    
    # Insert default tenant
    op.bulk_insert(tenant_table, [{'name': 'System Default'}])
    
    # Add column as nullable=True
    op.add_column('students', sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    # Update existing rows to reference the first tenant (id 1)
    op.execute('UPDATE students SET tenant_id = 1')
    
    # Alter column to be nullable=False
    op.alter_column('students', 'tenant_id', nullable=False)
    
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'students', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_column('students', 'tenant_id')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
